apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: hello-world-ingress
  namespace: spinnaker
spec:
  rules:
    - host: spinnaker-ofer-cd.mbedcloudintegration.net
      http:
        paths:
          - backend:
              serviceName: hello-kubernetes
              servicePort: 80
  tls:
    - hosts:
        - hello-world.example.com
      secretName: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  namespace: spinnaker
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - image: 'paulbouwer/hello-kubernetes:1.5'
          name: hello-kubernetes
          ports:
            - containerPort: 8080